---
title: "lab1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem1 (a)
```{r}
# read pro distribution
mk <- read.table('Markov100.txt', header=FALSE)
p <- as.matrix(mk)
# set initial vector
a <- rep_len(0, 100)
a[1] = 1
# get prob of being at stage 5 after 10 transitions
library(expm)
p_5 <- a %*% (p %^%10)
print(paste0('The probability of being at stage 5 after 10 transitions is: ', p_5[1,5]))
```

# Problem1 (b)
```{r}
# start from stage 1
a1 <- rep_len(0, 100)
a1[1] <- 1
p1_10 <- a1 %*% (p %^%10)
# start from stage 2
a2 <- rep_len(0, 100)
a2[2] <- 1
p2_10 <- a2 %*% (p %^%10)
# start from stage 3
a3 <- rep_len(0, 100)
a3[3] <- 1
p3_10 <- a3 %*% (p %^%10)
p_10_b <- (1/3) * (p1_10[1, 10] + p2_10[1, 10] + p3_10[1, 10])
print(paste0('If we start from 1, 2, 3 with equal probability, the probability of being at stage 5 after 10 transitions is: ', p_10_b))
```

# Problem1 (c)
```{r}
Q <- t(p) - diag(100)
Q[100,] <- rep_len(1, 100)
rhs <- rep_len(0, 100)
rhs[100] <- 1
Pi <- solve(Q) %*% rhs
print(paste0('The steady state probability of being in State 1 is: ', Pi[1]))
```

# Problem1 (d)
```{r}
B <- p[1:99, 1:99]
Q <- diag(99) - B
e <- rep_len(1, 99)
m <- solve(Q) %*% e
print(paste0('The mean first passage time from State 1 to State 100 is: ', m[1]))
```

# Problem2 (a)
```{r}
web <- read.table('webtraffic.txt', header=TRUE)
# traffic count
traffic <- t(matrix(c(colSums(web)), nrow = 9, ncol = 9))
print(traffic)
```

# Problem2 (b)
```{r}
traffic[9,1] = 1000
# construct probability distribution
p <- traffic/rowSums(traffic)
print(p)
```

# Problem2 (c)
```{r}
Q <- t(p) - diag(9)
Q[9,] <- c(1, 1, 1, 1, 1, 1, 1, 1, 1)
rhs <- c(0, 0, 0, 0, 0, 0, 0, 0, 1)
Pi <- solve(Q) %*% rhs
print(Pi)
```

# Problem2 (d)
```{r}
time <- c(0.1, 2, 3, 5, 5, 3, 3, 2, 0)
# mean passenger time
B <- p[1:8, 1:8]
Q <- diag(8) - B
e <- rep_len(1, 8)
m <- solve(Q) %*% e
page <- m[1]
avg_time <- time %*% Pi
print('the average time a visitor spend on the website')
print(avg_time*page)
```

# Problem2 (e)
```{r}
# new traffic count
traffic2 <- traffic
traffic2[2,6] <- traffic[2,6] + 0.3 * traffic[2,3]
traffic2[2,3] <- 0.7 * traffic[2,3]
traffic2[2,7] <- traffic[2,7] + 0.2 * traffic[2,4]
traffic2[2,4] <- 0.8 * traffic[2,4]
print('New Traffic Count')
print(traffic2)
# construct new probability distribution
p2 <- traffic2/rowSums(traffic2)
print('New Probability Distribution')
print(p2)
# new Pi2
Q2 <- t(p2) - diag(9)
Q2[9,] <- c(1, 1, 1, 1, 1, 1, 1, 1, 1)
rhs2 <- c(0, 0, 0, 0, 0, 0, 0, 0, 1)
Pi2 <- solve(Q2) %*% rhs2
print('New steady state probability vector Pi2')
print(Pi2)
# compare variance
var1 <- var(Pi)
var2 <- var(Pi2)
print(paste0('variance before: ', var1))
print(paste0('variance after: ', var2))
```

The variance of Pi2 is smaller than variance of Pi, so the link helped balancing the traffic.